
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EPSILON LETTER LPAREN PLUS RPAREN SEMI STARreStart : re SEMIre : termre : re PLUS termterm : factorterm : term factorfactor : nigglefactor : factor STARniggle : LETTERniggle : EPSILONniggle : LPAREN re RPAREN'
    
_lr_action_items = {'LETTER':([0,3,4,5,6,7,8,10,11,12,14,15,],[6,6,-4,-6,-8,-9,6,6,-5,-7,6,-10,]),'EPSILON':([0,3,4,5,6,7,8,10,11,12,14,15,],[7,7,-4,-6,-8,-9,7,7,-5,-7,7,-10,]),'LPAREN':([0,3,4,5,6,7,8,10,11,12,14,15,],[8,8,-4,-6,-8,-9,8,8,-5,-7,8,-10,]),'$end':([1,9,],[0,-1,]),'SEMI':([2,3,4,5,6,7,11,12,14,15,],[9,-2,-4,-6,-8,-9,-5,-7,-3,-10,]),'PLUS':([2,3,4,5,6,7,11,12,13,14,15,],[10,-2,-4,-6,-8,-9,-5,-7,10,-3,-10,]),'RPAREN':([3,4,5,6,7,11,12,13,14,15,],[-2,-4,-6,-8,-9,-5,-7,15,-3,-10,]),'STAR':([4,5,6,7,11,12,15,],[12,-6,-8,-9,12,-7,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'reStart':([0,],[1,]),'re':([0,8,],[2,13,]),'term':([0,8,10,],[3,3,14,]),'factor':([0,3,8,10,14,],[4,11,4,4,11,]),'niggle':([0,3,8,10,14,],[5,5,5,5,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> reStart","S'",1,None,None,None),
  ('reStart -> re SEMI','reStart',2,'p_reStart','REParser.py',6),
  ('re -> term','re',1,'p_re_1','REParser.py',10),
  ('re -> re PLUS term','re',3,'p_re_2','REParser.py',15),
  ('term -> factor','term',1,'p_term_1','REParser.py',24),
  ('term -> term factor','term',2,'p_term_2','REParser.py',29),
  ('factor -> niggle','factor',1,'p_factor_1','REParser.py',37),
  ('factor -> factor STAR','factor',2,'p_factor_2','REParser.py',41),
  ('niggle -> LETTER','niggle',1,'p_niggle_1','REParser.py',48),
  ('niggle -> EPSILON','niggle',1,'p_niggle_2','REParser.py',56),
  ('niggle -> LPAREN re RPAREN','niggle',3,'p_niggle_3','REParser.py',63),
]
